image: debian/sid
secrets:
  - ccb6777e-650b-4fa2-87e1-e2342f5bb605  # tzpfms SSH key
packages:
  - clang
  - pkg-config
  - libtss2-dev
  - libtspi-dev
  - ronn
tasks:
  - get-zfs: |
      sudo sed -i 's/main/main contrib non-free/' /etc/apt/sources.list
      sudo apt update
      sudo apt install -y libzfslinux-dev
  - build-gcc: |
      cd tzpfms
      make
      find out/ -maxdepth 1 -type f -exec readelf -d {} +
      make clean
  - build-clang: |
      cd tzpfms
      CC=clang CXX=clang++ make
      find out/ -maxdepth 1 -type f -exec readelf -d {} +
  - manpages: |
      git -C tzpfms/ worktree add ../tzpfms-man man
      cd tzpfms-man
      git ls-tree -z --name-only HEAD | xargs -0 rm -r
      mv ../tzpfms/out/man/* .
      git add .
      git config user.email "nabijaczleweli/autouploader@nabijaczleweli.xyz"
      git config user.name "наб autouploader"
      git commit -m "Manpage update by job $JOB_ID" || exit 0
      git remote set-url origin 'git@git.sr.ht:~nabijaczleweli/tzpfms'
      ssh-keyscan git.sr.ht > ~/.ssh/known_hosts
      git push
